services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=data
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    networks:
      - mi-red

  backend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    networks:
      - mi-red
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src # Montar el código fuente
    depends_on:
      - db

networks:
  mi-red: